version: '3'
services:
  influxdb:
    image: xshrim/k6_influxdb
    ports:
      - "8086:8086"
  grafana:
    image: xshrim/k6_grafana
    links:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - "3000:3000"
  k6:
    image: xshrim/k6_k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./sample.js:/scripts/sample.js
    command: 'run /scripts/sample.js' 
